### ISSUE TITLE
Publish as a 3rd party CoronaSDK plugin

### ISSUE THREAD

**Issue by endel** [dmccuskey/DMC-Corona-Library#31]
Hi @dmccuskey,

Thanks a lot for this library! It would be great to have a CoronaSDK plugin of it available here: https://store.coronalabs.com/plugins

Cheers!

**Comment by dmccuskey** [comment]
hey @endel 

i'm glad that to know that you're getting use out of the dmc-lib ! 

i would have pushed it awhile ago, but the rules read that the author had to promise to support the plugin. i've since moved away from the Corona platform, thus can't make that promise.

cheers, dmc
